VANILLA_KEYBLADE_STATS = [
    {"STR":  3, "CRR":  20, "CRB":  0, "REC": 30, "MP":  0}, # Kingdom Key
    {"STR":  1, "CRR":  20, "CRB":  0, "REC": 30, "MP":  0}, # Dream Sword
    {"STR":  1, "CRR":   0, "CRB":  0, "REC": 60, "MP":  0}, # Dream Shield
    {"STR":  1, "CRR":  10, "CRB":  0, "REC": 30, "MP":  0}, # Dream Rod
    {"STR":  0, "CRR":  20, "CRB":  0, "REC": 30, "MP":  0}, # Wooden Sword
    {"STR":  5, "CRR":  10, "CRB":  0, "REC":  1, "MP":  0}, # Jungle King
    {"STR":  6, "CRR":  20, "CRB":  0, "REC": 60, "MP":  0}, # Three Wishes
    {"STR":  8, "CRR":  10, "CRB":  2, "REC": 30, "MP":  1}, # Fairy Harp
    {"STR":  7, "CRR":  40, "CRB":  0, "REC":  1, "MP":  0}, # Pumpkinhead
    {"STR":  6, "CRR":  20, "CRB":  0, "REC": 30, "MP":  1}, # Crabclaw
    {"STR": 13, "CRR":  40, "CRB":  0, "REC": 60, "MP":  0}, # Divine Rose
    {"STR":  4, "CRR":  20, "CRB":  0, "REC": 30, "MP":  2}, # Spellbinder
    {"STR": 10, "CRR":  20, "CRB":  2, "REC": 90, "MP":  0}, # Olympia
    {"STR": 10, "CRR":  20, "CRB":  0, "REC": 30, "MP":  1}, # Lionheart
    {"STR":  9, "CRR":   2, "CRB":  0, "REC": 90, "MP": -1}, # Metal Chocobo
    {"STR":  9, "CRR":  40, "CRB":  0, "REC":  1, "MP":  1}, # Oathkeeper
    {"STR": 11, "CRR":  20, "CRB":  2, "REC": 30, "MP": -1}, # Oblivion
    {"STR":  7, "CRR":  20, "CRB":  0, "REC":  1, "MP":  2}, # Lady Luck
    {"STR":  5, "CRR": 200, "CRB":  2, "REC":  1, "MP":  0}, # Wishing Star
    {"STR": 14, "CRR":  40, "CRB":  2, "REC": 90, "MP":  2}, # Ultima Weapon
    {"STR":  3, "CRR":  20, "CRB":  0, "REC":  1, "MP":  3}, # Diamond Dust
    {"STR":  8, "CRR":  10, "CRB": 16, "REC": 90, "MP": -2}, # One-Winged Angel
    ]
VANILLA_PUPPY_LOCATIONS = [
    "Traverse Town Mystical House Glide Chest",
    "Traverse Town Alleyway Behind Crates Chest",
    "Traverse Town Item Workshop Left Chest",
    "Traverse Town Secret Waterway Near Stairs Chest",
    "Wonderland Queen's Castle Hedge Right Blue Chest",
    "Wonderland Lotus Forest Nut Chest",
    "Wonderland Tea Party Garden Above Lotus Forest Entrance 1st Chest",
    "Olympus Coliseum Coliseum Gates Right Blue Trinity Chest",
    "Deep Jungle Hippo's Lagoon Center Chest",
    "Deep Jungle Vines 2 Chest",
    "Deep Jungle Waterfall Cavern Middle Chest",
    "Deep Jungle Camp Blue Trinity Chest",
    "Agrabah Cave of Wonders Treasure Room Across Platforms Chest",
    "Halloween Town Oogie's Manor Hollow Chest",
    "Neverland Pirate Ship Deck White Trinity Chest",
    "Agrabah Cave of Wonders Hidden Room Left Chest",
    "Agrabah Cave of Wonders Entrance Tall Tower Chest",
    "Agrabah Palace Gates High Opposite Palace Chest",
    "Monstro Chamber 3 Platform Above Chamber 2 Entrance Chest",
    "Wonderland Lotus Forest Through the Painting Thunder Plant Chest",
    "Hollow Bastion Grand Hall Left of Gate Chest",
    "Halloween Town Cemetery By Cat Shape Chest",
    "Halloween Town Moonlight Hill White Trinity Chest",
    "Halloween Town Guillotine Square Pumpkin Structure Right Chest",
    "Monstro Mouth High Platform Across from Boat Chest",
    "Monstro Chamber 6 Low Chest",
    "Monstro Chamber 5 Atop Barrel Chest",
    "Neverland Hold Flight 1st Chest",
    "Neverland Hold Yellow Trinity Green Chest",
    "Neverland Captain's Cabin Chest",
    "Hollow Bastion Rising Falls Floating Platform Near Save Chest",
    "Hollow Bastion Castle Gates Gravity Chest",
    "Hollow Bastion Lift Stop Outside Library Gravity Chest"
    ]
CHAR_TO_KH = {
    "{eol}": 0x00,
    " ":  0x01,
    "\n": 0x02,
    "{lf}": 0x02,
    "{0x03}": 0x03,
    "{0x04}": 0x04,
    "{0x05}": 0x05,
    "{0x06}": 0x06,
    "{0x08}": 0x08,
    "{0x09}": 0x09,
    "{0x0A}": 0x0A,
    "{0x0B}": 0x0B,
    "{0x0C}": 0x0C,
    "{0x0D}": 0x0D,
    "{0x0E}": 0x0E,
    "{0x0F}": 0x0F,
    "{0x10}": 0x10,
    "{0x11}": 0x11,
    "{0x12}": 0x12,
    "{0x13}": 0x13,
    "{0x14}": 0x14,
    "{0x16}": 0x16,
    "{0x18}": 0x18,
    "{0x19}": 0x19,
    "{0x1A}": 0x1A,
    "{0x1B}": 0x1B,
    "—":  0x20,
    "0":  0x21,
    "1":  0x22,
    "2":  0x23,
    "3":  0x24,
    "4":  0x25,
    "5":  0x26,
    "6":  0x27,
    "7":  0x28,
    "8":  0x29,
    "9":  0x2A,
    "A":  0x2B,
    "B":  0x2C,
    "C":  0x2D,
    "D":  0x2E,
    "E":  0x2F,
    "F":  0x30,
    "G":  0x31,
    "H":  0x32,
    "I":  0x33,
    "J":  0x34,
    "K":  0x35,
    "L":  0x36,
    "M":  0x37,
    "N":  0x38,
    "O":  0x39,
    "P":  0x3A,
    "Q":  0x3B,
    "R":  0x3C,
    "S":  0x3D,
    "T":  0x3E,
    "U":  0x3F,
    "V":  0x40,
    "W":  0x41,
    "X":  0x42,
    "Y":  0x43,
    "Z":  0x44,
    "a":  0x45,
    "b":  0x46,
    "c":  0x47,
    "d":  0x48,
    "e":  0x49,
    "f":  0x4A,
    "g":  0x4B,
    "h":  0x4C,
    "i":  0x4D,
    "j":  0x4E,
    "k":  0x4F,
    "l":  0x50,
    "m":  0x51,
    "n":  0x52,
    "o":  0x53,
    "p":  0x54,
    "q":  0x55,
    "r":  0x56,
    "s":  0x57,
    "t":  0x58,
    "u":  0x59,
    "v":  0x5A,
    "w":  0x5B,
    "x":  0x5C,
    "y":  0x5D,
    "z":  0x5E,
    "!":  0x5F,
    "?": 0x60,
    "&": 0x61,
    "%": 0x62,
    "+": 0x63,
    "{-}": 0x64,
    "{mX}": 0x65,
    "/": 0x66,
    "*": 0x67,
    ".": 0x68,
    ",": 0x69,
    "・": 0x6A,
    ":": 0x6B,
    ";": 0x6C,
    "…": 0x6D,
    "-": 0x6E,
    "ー": 0x6F,
    "~": 0x70,
    "'": 0x71,
    "\"": 0x72,
    "{゛b}": 0x73,
    "(": 0x74,
    ")": 0x75,
    "[": 0x76,
    "]": 0x77,
    "<": 0x78,
    ">": 0x79,
    "★": 0x7A,
    "☆": 0x7B,
    "↑": 0x7C,
    "↓": 0x7D,
    "→": 0x7E,
    "←": 0x7F,
    "●": 0x80,
    "■": 0x81,
    "{iPotion}": 0x82,
    "{iTent}": 0x83,
    "{iGem}": 0x84,
    "{iAbility}": 0x85,
    "{iKey}": 0x86,
    "{iStaff}": 0x87,
    "{iShield}": 0x88,
    "{iRing}": 0x89,
    "{iHat}": 0x8A,
    "{iMickey}": 0x8B,
    "○": 0x8C,
    "×": 0x8D,
    "△": 0x8E,
    "□": 0x8F,
    "▲": 0x90,
    "▼": 0x91,
    "►": 0x92,
    "◄": 0x93,
    "{iGummi1}": 0x94,
    "{iGummi2}": 0x95,
    "{iGummi3}": 0x96,
    "{iGummi4}": 0x97,
    "{iGummi5}": 0x98,
    "{iGummi6}": 0x99,
    "{iGummi7}": 0x9A,
    "{iGummi8}": 0x9B,
    "{iGummi9}": 0x9C,
    "{iGummi10}": 0x9D,
    "{0x9E}": 0x9E,
    "{0x9F}": 0x9F,
    "{0xA0}": 0xA0,
    "{0xA1}": 0xA1,
    "{0xA2}": 0xA2,
    "{0xA3}": 0xA3,
    "{0xA4}": 0xA4,
    "{0xA5}": 0xA5,
    "{0xA6}": 0xA6,
    "{0xA7}": 0xA7,
    "{0xA8}": 0xA8,
    "®":      0xA9,
    "{0xAA}": 0xAA,
    "{0xAB}": 0xAB,
    "{0xAC}": 0xAC,
    "{0xAD}": 0xAD,
    "{0xAE}": 0xAE,
    "{0xAF}": 0xAF,
    "{0xB0}": 0xB0,
    "{0xB1}": 0xB1,
    "{0xB2}": 0xB2,
    "{0xB3}": 0xB3,
    "{0xB4}": 0xB4,
    "{0xB5}": 0xB5,
    "{0xB6}": 0xB6,
    "{0xB7}": 0xB7,
    "{0xB8}": 0xB8,
    "{0xB9}": 0xB9,
    "{0xBA}": 0xBA,
    "{0xBB}": 0xBB,
    "{0xBC}": 0xBC,
    "{0xBD}": 0xBD,
    "{0xBE}": 0xBE,
    "{0xBF}": 0xBF,
    "{0xC0}": 0xC0,
    "{0xC1}": 0xC1,
    "{0xC2}": 0xC2,
    "{0xC3}": 0xC3,
    "{III}": 0xC4,
    "{VII}": 0xC5,
    "{VIII}": 0xC6,
    "{X}": 0xC7,
    "Œ": 0xC8,
    "œ": 0xC9,
    "¡": 0xCA,
    "¿": 0xCB,
    "À": 0xCC,
    "Á": 0xCD,
    "Â": 0xCE,
    "Ä": 0xCF,
    "Ç": 0xD0,
    "È": 0xD1,
    "É": 0xD2,
    "Ê": 0xD3,
    "Ë": 0xD4,
    "Ì": 0xD5,
    "Í": 0xD6,
    "Î": 0xD7,
    "Ï": 0xD8,
    "Ñ": 0xD9,
    "Ò": 0xDA,
    "Ó": 0xDB,
    "Ô": 0xDC,
    "Ö": 0xDD,
    "Ù": 0xDE,
    "Ú": 0xDF,
    "Û": 0xE0,
    "Ü": 0xE1,
    "ß": 0xE2,
    "à": 0xE3,
    "á": 0xE4,
    "â": 0xE5,
    "ä": 0xE6,
    "ç": 0xE7,
    "è": 0xE8,
    "é": 0xE9,
    "ê": 0xEA,
    "ë": 0xEB,
    "ì": 0xEC,
    "í": 0xED,
    "î": 0xEE,
    "ï": 0xEF,
    "ñ": 0xF0,
    "ò": 0xF1,
    "ó": 0xF2,
    "ô": 0xF3,
    "ö": 0xF4,
    "ù": 0xF5,
    "ú": 0xF6,
    "û": 0xF7,
    "ü": 0xF8,
    "°": 0xF9,
    "{---}": 0xFA,
    "》": 0xFB,
    "《": 0xFC,
    "{0xFD}": 0xFD,
    "{0xFE}": 0xFE,
    "{0xFF}": 0xFF,
    }

VANILLA_ABILITY_AP_COSTS = [
    {"Ability Name": "Treasure Magnet", "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Combo Plus",      "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Air Combo Plus",  "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Critical Plus",   "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Second Wind",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Scan",            "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Sonic Blade",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Ars Arcanum",     "AP Cost": 4, "Randomize": True},
    {"Ability Name": "Strike Raid",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Ragnarok",        "AP Cost": 4, "Randomize": True},
    {"Ability Name": "Trinity Limit",   "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Cheer",           "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Vortex",          "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Aerial Sweep",    "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Counter Attack",  "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Blitz",           "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Guard",           "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Dodge Roll",      "AP Cost": 1, "Randomize": True},
    {"Ability Name": "MP Haste",        "AP Cost": 3, "Randomize": True},
    {"Ability Name": "MP Rage",         "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Second Chance",   "AP Cost": 5, "Randomize": True},
    {"Ability Name": "Berserk",         "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Jackpot",         "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Lucky Strike",    "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Charge",          "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Rocket",          "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Tornado",         "AP Cost": 2, "Randomize": True},
    {"Ability Name": "MP Gift",         "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Raging Boar",     "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Asp's Bite",      "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Healing Herb",    "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Wind Armor",      "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Crescent",        "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Sandstorm",       "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Applause!",       "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Blazing Fury",    "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Icy Terror",      "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Bolts of Sorrow", "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Ghostly Scream",  "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Hummingbird",     "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Time-Out",        "AP Cost": 4, "Randomize": True},
    {"Ability Name": "Storm´s Eye",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Ferocious Lunge", "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Furious Bellow",  "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Spiral Wave",     "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Thunder Potion",  "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Cure Potion",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Aero Potion",     "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Slapshot",        "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Sliding Dash",    "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Hurricane Blast", "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Ripple Drive",    "AP Cost": 3, "Randomize": True},
    {"Ability Name": "Stun Impact",     "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Gravity Break",   "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Zantetsuken",     "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Tech Boost",      "AP Cost": 2, "Randomize": True},
    {"Ability Name": "Encounter Plus",  "AP Cost": 1, "Randomize": True},
    {"Ability Name": "Leaf Bracer",     "AP Cost": 5, "Randomize": True},
    {"Ability Name": "Evolution",       "AP Cost": 3, "Randomize": True},
    {"Ability Name": "EXP Zero",        "AP Cost": 0, "Randomize": True},
    {"Ability Name": "Combo Master",    "AP Cost": 3, "Randomize": True}
    ]

WORLD_KEY_ITEMS = {
    "Footprints": "Wonderland",
    "Entry Pass": "Olympus Coliseum",
    "Slides": "Deep Jungle",
    "Crystal Trident": "Atlantica",
    "Forget-Me-Not": "Halloween Town",
    "Jack-In-The-Box": "Halloween Town",
    "Theon Vol. 6": "Hollow Bastion"
}

SPELL_ITEM_NAMES = ["Progressive Fire", "Progressive Blizzard", "Progressive Thunder", "Progressive Cure", "Progressive Gravity", "Progressive Stop", "Progressive Aero"]
OFFENSIVE_SPELL_ITEM_NAMES = ["Progressive Fire", "Progressive Blizzard", "Progressive Thunder", "Progressive Gravity", "Progressive Stop"]
VANILLA_SPELL_COSTS_LVL = [30, 30, 30, 30, 30, 30, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 200, 200, 200, 200, 200]
VANILLA_SPELL_COSTS_SPELL = [30, 30, 100, 100, 100, 200, 200]
POSSIBLE_SPELL_COSTS = [15, 30, 100, 200, 300] #60, 90

LOGIC_BEGINNER = 0
LOGIC_NORMAL = 5
LOGIC_PROUD = 10
LOGIC_MINIMAL = 15

ITEMHELP = [
    "Restores 30 HP of one character{0x0D} {eol}.{lf}Can be equipped by party members.",
    "Restores 60 HP of one character{0x0D} {eol}.{lf}Can be equipped by party members.",
    "Restores 3 MP of one character.{lf}Can be equipped by party members.",
    "Fully restores a character's HP and MP.{lf}Can be equipped by party members.",
    "",
    "Restores 30 HP of each party member{0x0D} {eol}.{lf}Can be equipped by party members.",
    "Restores 3 MP of each party member{0x0D} {eol}.{lf}Can be equipped by party members.",
    "Fully restores the party's HP and MP.{lf}Can be equipped by party members.",
    "Allows progression in 100 Acre Wood.",
    "Manifests the Door in Final Rest.",
    "Allows travel to Destiny Islands.{lf}Seashore is added as a landing option for{lf}Traverse Town.",
    "Allows progression in Destiny Islands.",
    "A mysterious stone filled with ice.{lf}Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "A mysterious stone filled with lightning.{lf}Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "A mysterious stone filled with light.{lf}Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "A mysterious stone filled with wind.{lf}Used for item synthesis.{lf}[Rarity: ★★★★★]",
    "Slightly raises Defense.",
    "Raises Defense.",
    "Significantly raises Defense.",
    "Reduces fire damage by 20{0x0D} {eol}%{lf}and slightly raises Defense.{lf}Equip more to boost effect.",
    "Reduces fire damage by 20{0x0D} {eol}%{lf}and raises Defense.{lf}Equip more to boost effect.",
    "Reduces fire damage by 20{0x0D} {eol}%{lf}and significantly raises Defense.{lf}Equip more to boost effect.",
    "Reduces ice damage by 20{0x0D} {eol}%{lf}and slightly raises Defense.{lf}Equip more to boost effect.",
    "Reduces ice damage by 20{0x0D} {eol}%{lf}and raises Defense.{lf}Equip more to boost effect.",
    "Reduces ice damage by 20{0x0D} {eol}%{lf}and significantly raises Defense.{lf}Equip more to boost effect.",
    "Reduces lightning damage by 20{0x0D} {eol}%{lf}and slightly raises Defense.{lf}Equip more to boost effect.",
    "Reduces lightning damage by 20{0x0D} {eol}%{lf}and raises Defense.{lf}Equip more to boost effect.",
    "Reduces lightning damage by 20{0x0D} {eol}%{lf}and significantly raises Defense.{lf}Equip more to boost effect.",
    "Slightly raises max AP.",
    "Raises max AP and Defense.",
    "Significantly raises max AP and{lf}Defense.",
    "Reduces dark damage by 20{0x0D} {eol}%{lf}and slightly raises Defense.{lf}Equip more to boost effect.",
    "Reduces dark damage by 20{0x0D} {eol}%{lf}and raises Defense.{lf}Equip more to boost effect.",
    "Reduces fire, ice, and lightning{lf}damage by 20{0x0D} {eol}% and raises Defense.{lf}Equip more to boost effect.",
    "Reduces fire, ice, and lightning damage{lf}by 20{0x0D} {eol}% and significantly raises Defense.{lf}Equip more to boost effect.",
    "Slightly raises Strength.",
    "Raises Strength and Defense.",
    "Significantly raises Strength{lf}and Defense.",
    "Slightly raises max HP and Defense.",
    "Raises max HP and Defense.",
    "Significantly raises max HP{lf}and Defense.",
    "Slightly raises max MP. Also{lf}enhances magic and summon power.",
    "Slightly raises max MP and Defense.{lf}Also enhances magic and summon power.",
    "Raises max MP and Defense.{lf}Also significantly enhances{lf}magic and summon power.",
    "Raises max HP and Defense, and{lf}reduces dark damage by 20{0x0D} {eol}%.{lf}Equip more to boost effect.",
    "Reduces all elemental damage by 20{0x0D} {eol}%.{lf}Equip more to boost effect.",
    "Raises max HP, max MP, max AP,{lf}Strength, and Defense. Also{lf}enhances magic and summon power.",
    "Slightly raises max HP and Strength.",
    "Reduces fire damage by 20{0x0D} {eol}% and{lf}raises max AP and Defense.",
    "Reduces fire and dark damage by 20{0x0D} {eol}%.{lf}Also raises Defense.",
    "Slightly raises Strength,{lf}Defense, and max AP.",
    "Slightly raises max HP and MP.{lf}Also enhances magic and summon power.",
    "Reduces fire, ice, and lightning{lf}damage by 20{0x0D} {eol}%. Also raises max AP.",
    "Reduces dark damage by 20{0x0D} {eol}%.{lf}Also raises Strength and Defense.",
    "Raises max HP, Strength, and Defense.",
    "Increases experience obtained by 20%. {lf}Equip more to boost effect.",
    "",
    "Increases experience obtained by 20% {lf}and slightly raises max MP.",
    "Increases experience obtained by 30%, {lf}but reduces Strength and Defense. {lf}Equip more to boost effect.",
    "Increases experience obtained by 30%, {lf}and slightly raises max AP.",
    "Reduces fire damage by 20%, {lf}and raises Strength and Defense. {lf}Equip more to boost effect.",
    "Reduces ice damage by 20%, {lf}and raises Strength and Defense. {lf}Equip more to boost effect.",
    "Reduces lightning damage by 20%, {lf}and raises Strength and Defense. {lf}Equip more to boost effect.",
    "Reduces fire damage by 40%, {lf}and raises Strength.",
    "Reduces ice damage by 40%, and {lf}raises max MP. Also enhances {lf}magic and summon power.",
    "Reduces lightning damage by 40%, {lf}and raises max AP.",
    "Raises max HP, max MP, and max AP. {lf}Also enhances magic and summon power.",
    "Greatly raises max HP, max MP, and max AP. {lf}Also enhances magic and summon power.",
    "Reduces fire, ice, and lightning damage {lf}by 20%. Raises max MP, but reduces {lf}Strength.",
    "Greatly reduces Strength, {lf}but greatly increases Defense.",
    "Reduces dark damage by 20%, {lf}and slightly raises Strength. {lf}Equip more to boost effect.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "The key chain attached draws out{lf}the Keyblade's true form and power.",
    "???",
    "???",
    "???",
    "A toy sword made of wood.",
    "Has a long reach, but seldom{lf}deals critical blows.",
    "A powerful weapon that is{lf}difficult to deflect.",
    "Raises max MP by 1, and enhances{lf}magic and summon power. Sometimes{lf}deals powerful critical blows.",
    "Has a long reach and the ability to{lf}deal a string of critical blows.",
    "Raises max MP by 1, and enhances{lf}magic and summon power. Also deals{lf}good physical damage.",
    "A powerful weapon that is difficult{lf}to deflect. Capable of dealing a{lf}string of critical blows.",
    "Raises max MP by 2, and significantly{lf}enhances magic and summon power.",
    "A powerful weapon that is difficult{lf}to deflect. Capable of inflicting{lf}mighty critical blows.",
    "Raises max MP by 1, and enhances{lf}magic and summon power. Also deals{lf}great physical damage.",
    "Possesses incredible power and{lf}reach, but reduces max MP by 1.{lf}Rarely deals critical blows.",
    "Raises max MP by 1, and enhances{lf}magic and summon power. Capable of{lf}dealing a string of critical blows.",
    "Possesses colossal power,{lf}but reduces max MP by 1.",
    "Raises max MP by 2, and significantly{lf}enhances magic and summon power. Also{lf}inflicts good physical damage.",
    "Has a short reach, but always{lf}finishes up a combo attack with{lf}a powerful critical blow.",
    "The ultimate Keyblade. Raises{lf}max MP by 2, and possesses{lf}maximum power and attributes.",
    "Greatly enhances magic and summon power. {lf}Raises max MP by 3.",
    "Has little power, but sometimes deals {lf}extremely powerful critical blows. Reduces {lf}max MP by 2.",
    "A staff that heightens magic power.",
    "A staff that heightens magic power.{lf}Can also be used for physical attacks.",
    "A staff that heightens magic power.{lf}Also fairly good for physical attacks.",
    "A mystical staff brimming with power.{lf}Raises max MP by 1.",
    "A mystical staff brimming with power.{lf}Raises max MP by 1. Also fairly good{lf}for physical attacks.",
    "A hammer made for combat.{lf}Reduces max MP by 1.",
    "A powerful hammer made for combat.{lf}Reduces max MP by 1.",
    "A tremendously powerful{lf}hammer made for combat.{lf}Reduces max MP by 1.",
    "A staff strong in both{lf}physical and magical power.{lf}Raises max MP by 1.",
    "A rod that sometimes{lf}inflicts massive damage.{lf}Reduces max MP by 1.",
    "A mysterious rod holding unknown{lf}power. Raises max MP by 2.",
    "A staff of immense magical{lf}and physical power.{lf}Raises max MP by 2.",
    "An enormously powerful staff{lf}sometimes left behind by Wizards.{lf}Raises max MP by 2.",
    "The most powerful staff. {lf}Sometimes deals critical blows.",
    "A staff that focuses solely on {lf}magic. Raises max MP by 3.",
    "",
    "A standard-issue knight's shield.",
    "A shield that strikes a fine balance{lf}between attack and defense.",
    "A well-balanced and effective shield{lf}for both attack and defense.",
    "A large shield better suited for{lf}defense than offense. Effective{lf}against various forms of attack.",
    "A large shield best suited for{lf}defense.{lf}Also an effective assault weapon.",
    "A large shield best suited for defense.{lf}Effective against various attacks, and{lf}also a powerful assault weapon.",
    "A shield made for attack{lf}rather than defense.{lf}Small and easy to handle.",
    "A small, powerful shield made{lf}for attack rather than defense.",
    "A shield of surpassing offensive{lf}and defensive strength.",
    "A shield with enormous power{lf}sealed within. Made for attacking.",
    "A shield to protect loved ones.{lf}Raises max MP by 2.",
    "A royally powerful shield.{lf}Raises max MP by 2.",
    "A rugged shield sometimes{lf}left behind by Defenders.{lf}Raises max MP by 1.",
    "The most powerful shield. {lf}Small, but effective.",
    "A shield that focuses solely on {lf}magic. Raises max MP by 3.",
    "",
    "Tarzan's weapon.{lf}Its long reach allows him{lf}to attack from a distance.",
    "",
    "Aladdin's weapon.{lf}Powerful and efficient.",
    "",
    "",
    "Peter Pan's weapon.{lf}Relatively weak, but easy to handle.",
    "",
    "Fully restores the party's HP.{lf}Can only be used from the menu.",
    "Restores all HP and 3 MP of each party{lf}member. Can only be used from the menu.",
    "Fully restores the party's HP and MP.{lf}Can only be used from the menu.",
    "",
    "",
    "",
    "",
    "Allows travel to Wonderland.",
    "Allows travel to Olympus Coliseum.",
    "Allows travel to Deep Jungle.",
    "Raises Strength by 1.{lf}Can only be used from the menu.",
    "Raises Defense by 1.{lf}Can only be used from the menu.",
    "Raises max AP by 1.{lf}Can only be used from the menu.",
    "Allows travel to Agrabah.",
    "Allows travel to Monstro.",
    "Allows travel to Atlantica.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Fire magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Blizzard magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Thunder magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Cure magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Gravity magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Stop magic. Its value is unknown.",
    "Proof that a White Mushroom{lf}acknowledged you a master of{lf}Aero magic. Its value is unknown.",
    "Allows travel to Neverland.",
    "Allows travel to Halloween Town.",
    "Number of puppies rescued.{lf}Return them Traverse Town.",
    "Allows travel to Hollow Bastion.",
    "Allows travel to End of the World.",
    "Allows interaction with Blue Trinity marks.",
    "Allows interaction with Red Trinity marks.",
    "Allows interaction with Green Trinity marks.",
    "Allows interaction with Yellow Trinity marks.",
    "Allows interaction with White Trinity marks.",
    "Allows Sora and Donald to cast Fire.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Blizzard.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Thunder.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Cure.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Gravity.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Stop.{lf}Acquire more to increase level.",
    "Allows Sora and Donald to cast Aero.{lf}Acquire more to increase level.",
    "Allows entrance to the Phil Cup.",
    "Allows access to the upper floor{lf}in Hollow Bastion Entrance Hall.",
    "Allows entrance to the Pegasus Cup.",
    "Allows entrance to the Hercules Cup.",
    "Used for item synthesis in Traverse Town.",
    "A book to be delivered to a{lf}house on the outskirts of town.{lf}Several pages are missing.",
    "Used to progress in Hollow Bastion (Flame).",
    "Used to progress in Hollow Bastion (Chest).",
    "Used to progress in Hollow Bastion (Statue).",
    "Used to progress in Hollow Bastion (Fountain).",
    "A log that washed up onto the shore.{lf}Needed to build the raft.",
    "A large sheet of white cloth.{lf}Needed to build the raft.",
    "A long, strong rope.{lf}Needed to build the raft.",
    "An egg with a very tough shell.{lf}A provision for the raft.",
    "A small fish caught in the shallows.{lf}A provision for the raft.",
    "A mushroom that thrives in the dark.{lf}A provision for the raft.",
    "A coconut from a coco palm tree.{lf}A provision for the raft.",
    "A bottle of pure, fresh water.{lf}A provision for the raft.",
    "Half of a gummi emitting a{lf}mysterious glow. Acquired in{lf}the Deep Jungle.",
    "Half of a gummi emitting a{lf}mysterious glow. Acquired in{lf}Wonderland.",
    "A gummi emitting a mysterious glow.",
    "Half of a gummi emitting a{lf}mysterious glow. Acquired in{lf}Traverse Town.",
    "Half of a gummi emitting a{lf}mysterious glow. Acquired in{lf}Neverland.",
    "A gummi emitting a mysterious glow.",
    "A gem emanating a strange vitality.{lf}Give it to the Fairy Godmother.",
    "A gem emanating a strange vitality.{lf}Give it to the Fairy Godmother.",
    "A gem emanating a strange vitality.{lf}Give it to the Fairy Godmother.",
    "A precious stone with mysterious{lf}power sealed within.",
    "Used to progress in Atlantica.",
    "Drop in Traverse Town mailbox.",
    "A page torn out of Merlin's book.{lf}Try reattaching it.",
    "A page torn out of Merlin's book.{lf}Try reattaching it.",
    "A page torn out of Merlin's book.{lf}Try reattaching it.",
    "A page torn out of Merlin's book.{lf}Try reattaching it.",
    "A page torn out of Merlin's book.{lf}Try reattaching it.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Deep Jungle.",
    "Used to progress in Wonderland.",
    "Left behind by the Heartless.{lf}They may help prove Alice's innocence.",
    "Left behind by the Heartless.{lf}It may help prove Alice's innocence.",
    "Left behind by the Heartless.{lf}It may help prove Alice's innocence.",
    "Used to progress in Halloween Town.",
    "Used to progress in Halloween Town.",
    "Used to progress in Olympus Coliseum.",
    "A placeholder for a remote item.{lf}The item can be for you or someone else.",
    "Allows summoning Dumbo.",
    "",
    "Allows summoning Bambi.",
    "Allows summoning Genie.",
    "Allows summoning Tinker Bell.",
    "Allows summoning Mushu.",
    "Allows summoning Simba.",
    "A macguffin.{lf}Something will happen if you acquire enough.",
    "Raises Max HP by 3.",
    "Raises Max MP by 1.",
    "Raises Max AP by 2.",
    "Raises Strength by 2.",
    "Raises Defense by 2.",
    "Raises Max Item Slots by 1.",
    "Raises Max Accessory Slots by 1.",
    "A gem containing essence of thunder.{lf}Used for item synthesis.{lf}[Rarity: ★★☆☆☆]",
    "A crystal bursting with the essence of three{lf}elements. Used for item synthesis.{lf}[Rarity: ★★★☆☆]",
    "A gem shard containing essence of vitality.{lf}Used for item synthesis.{lf}[Rarity: ★☆☆☆☆]",
    "A gem containing essence of vitality.{lf}Used for item synthesis.{lf}[Rarity: ★★☆☆☆]",
    "Crystallized essence of vitality.{lf}Used for item synthesis.{lf}[Rarity: ★★★☆☆]",
    "Droplet of a crystallized, mysterious{lf}substance. Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "A howling gale frozen in crystal form.{lf}Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "A mineral shard containing rare metal.{lf}Used for item synthesis.{lf}[Rarity: ★★☆☆☆]",
    "An extremely rare metal ore.{lf}Used for item synthesis.{lf}[Rarity: ★★★☆☆]",
    "A rare and most valuable ore.{lf}Used for item synthesis.{lf}[Rarity: ★★★★☆]",
    "",
    "synthesis.{lf}[Rarity: ★★★★☆]",
    "",
    "",
    "",
    "ÁÁÁÁÁÁÁÁÁÁ",
]

WORD = [
    "Attack",
    "Magic",
    "Items",
    "Talk",
    "Examine",
    "Summon",
    "Fire",
    "Fira",
    "Firaga",
    "Blizzard",
    "Blizzara",
    "Blizzaga",
    "Thunder",
    "Thundara",
    "Thundaga",
    "Cure",
    "Cura",
    "Curaga",
    "Gravity",
    "Gravira",
    "Graviga",
    "Stop",
    "Stopra",
    "Stopga",
    "Aero",
    "Aerora",
    "Aeroga",
    "Lift",
    "Drop",
    "Throw",
    "Potion",
    "Hi-Potion",
    "Ether",
    "Elixir",
    "",
    "Mega-Potion",
    "Mega-Ether",
    "Megalixir",
    "Torn Page",
    "Final Door Key",
    "Destiny Islands",
    "Raft Masterials",
    "Frost Stone",
    "Lightning Stone",
    "Dazzling Stone",
    "Stormy Stone",
    "Protect Chain",
    "Protera Chain",
    "Protega Chain",
    "Fire Ring",
    "Fira Ring",
    "Firaga Ring",
    "Blizzard  Ring",
    "Blizzara Ring",
    "Blizzaga Ring",
    "Thunder Ring",
    "Thundara Ring",
    "Thundaga Ring",
    "Ability Stud",
    "Guard Earring",
    "Master Earring",
    "Chaos Ring",
    "Dark Ring",
    "Element Ring",
    "Three Stars",
    "Power Chain",
    "Golem Chain",
    "Titan Chain",
    "Energy Bangle",
    "Angel Bangle",
    "Gaia Bangle",
    "Magic Armlet",
    "Rune Armlet",
    "Atlas Armlet",
    "Heartguard",
    "Ribbon",
    "Crystal Crown",
    "Brave Warrior",
    "Ifrit's Horn",
    "Inferno Band",
    "White Fang",
    "Ray of Light",
    "Holy Circlet",
    "Raven's Claw",
    "Omega Arts",
    "EXP Earring",
    "",
    "EXP Ring",
    "EXP Bracelet",
    "EXP Necklace",
    "Firagun Band",
    "Blizzagun Band",
    "Thundagun Band",
    "Ifrit Belt",
    "Shiva Belt",
    "Ramuh Belt",
    "Moogle Badge",
    "Cosmic Arts",
    "Royal Crown",
    "Prime Cap",
    "Obsidian Ring",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Kingdom Key",
    "Dream Sword",
    "Dream Shield",
    "Dream Rod",
    "Wooden Sword",
    "Jungle King",
    "Three Wishes",
    "Fairy Harp",
    "Pumpkinhead",
    "Crabclaw",
    "Divine Rose",
    "Spellbinder",
    "Olympia",
    "Lionheart",
    "Metal Chocobo",
    "Oathkeeper",
    "Oblivion",
    "Lady Luck",
    "Wishing Star",
    "Ultima Weapon",
    "Diamond Dust",
    "One{-}Winged Angel",
    "Mage's Staff",
    "Morning Star",
    "Shooting Star",
    "Magus Staff",
    "Wisdom Staff",
    "Warhammer",
    "Silver Mallet",
    "Grand Mallet",
    "Lord Fortune",
    "Violetta",
    "Dream Rod",
    "Save the Queen",
    "Wizard's Relic",
    "Meteor Strike",
    "Fantasista",
    "",
    "Knight's Shield",
    "Mythril Shield",
    "Onyx  Shield",
    "Stout Shield",
    "Golem Shield",
    "Adamant Shield",
    "Smasher",
    "Gigas Fist",
    "Genji Shield",
    "Herc's Shield",
    "Dream Shield",
    "Save the King",
    "Defender",
    "Mighty Shield",
    "Seven Elements",
    "",
    "Spear",
    "No Weapon",
    "Sword",
    "No Weapon",
    "No Weapon",
    "Dagger",
    "Claws",
    "Tent",
    "Camping Set",
    "Cottage",
    "",
    "",
    "",
    "",
    "Wonderland",
    "Olympus Coliseum",
    "Deep Jungle",
    "Power Up",
    "Defense Up",
    "AP Up",
    "Agrabah",
    "Monstro",
    "Atlantica",
    "Fire Arts",
    "Blizzard Arts",
    "Thunder Arts",
    "Cure Arts",
    "Gravity Arts",
    "Stop Arts",
    "Aero Arts",
    "Neverland",
    "Halloween Town",
    "Puppy",
    "Hollow Bastion",
    "End of the World",
    "Blue Trinity",
    "Red Trinity",
    "Green Trinity",
    "Yellow Trinity",
    "White Trinity",
    "Fire",
    "Blizzard",
    "Thunder",
    "Cure",
    "Gravity",
    "Stop",
    "Aero",
    "Phil Cup",
    "Theon vol. 6",
    "Pegasus Cup",
    "Hercules Cup",
    "Empty Bottle",
    "Old Book",
    "Emblem Piece",
    "Emblem Piece",
    "Emblem Piece",
    "Emblem Piece",
    "Log",
    "Cloth",
    "Rope",
    "Seagull Egg",
    "Fish",
    "Mushroom",
    "Coconut",
    "Drinking Water",
    "Navi-G Piece",
    "Navi-G Piece",
    "Navi-Gummi",
    "Navi-G Piece",
    "Navi-G Piece",
    "Navi-Gummi",
    "Watergleam",
    "Naturespark",
    "Fireglow",
    "Earthshine",
    "Crystal Trident",
    "Postcard",
    "Torn Page",
    "Torn Page",
    "Torn Page",
    "Torn Page",
    "Torn Page",
    "Slides",
    "Slide 2",
    "Slide 3",
    "Slide 4",
    "Slide 5",
    "Slide 6",
    "Footprints",
    "Claw Marks",
    "Stench",
    "Antenna",
    "Forget-Me-Not",
    "Jack-in-the-Box",
    "Entry Pass",
    "AP Item",
    "Dumbo",
    "",
    "Bambi",
    "Genie",
    "Tinker Bell",
    "Mushu",
    "Simba",
    "Lucky Emblem",
    "Max HP ↑",
    "Max MP ↑",
    "Max AP ↑",
    "Strength ↑",
    "Defense ↑",
    "Item Slot ↑",
    "Accessory Slot ↑",
    "Thunder Gem",
    "Shiny Crystal",
    "Bright Shard",
    "Bright Gem",
    "Bright Crystal",
    "Mystery Goo",
    "Gale",
    "Mythril Shard",
    "Mythril",
    "Orichalcum",
    "Dumbo",
    "Bambi",
    "Genie",
    "Tinker Bell",
    "Mushu",
    "Simba",
    "Bahamut",
    "Save",
    "Open",
    "Sora",
    "Donald",
    "Goofy",
    "Tarzan",
    "Pooh",
    "Aladdin",
    "Ariel",
    "Jack",
    "Peter Pan",
    "Beast",
    "ー",
    "Shortcut",
    "Max HP ↑",
    "Max MP ↑",
    "Max AP ↑",
    "Strength ↑",
    "Defense ↑",
    "Jump Next",
    "Jump On",
    "Splash",
    "Fire Breath",
    "Rush",
    "Test",
    "N/A",
    "Sonic",
    "All",
    "Rave",
    "Blast",
    "Dismiss",
    "Target",
    "Showtime",
    "Trinity",
    "Trinity",
    "N/A",
    "Open",
    "Examine",
    "Arcanum",
    "Bash",
    "Finish",
    "Ragnarok",
    "Impact",
    "Charge Up",
    "Proud Roar",
    "Strike",
    "Raid",
    "Judgment",
    "Freeze",
    "Hit",
    "Counter",
    "Learned  ",
    "Max items ↑",
    "Max accessories ↑",
    "Call",
    "Move",
    "Drink",
    "Eat",
    "Sit",
    "Push",
    "Read",
    "Touch",
    "Unlock",
    "Release",
    "Grab On",
    "Pull Out",
    "Take",
    "Turn",
    "Mail Card",
    "Get In",
    "Knock",
    "Pull",
    "Flower",
    "Cancel",
    "Jump Off",
    "Shock",
    "Release",
    "Ghost",
    "???",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "",
    "",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "9",
    "",
    "",
    "Á" 
]

SYSMSG = [
    "{0x08}{0xFF}{0xFF}{0xFF}●No controller detected.",
    "{0x0E}《{0xFF}Please reinsert {lf}the Kingdom Hearts game disc.",
    "Hard Disk Drive Error.{0x03}{0x1B}Refer to the Hard Disk Drive{0x03}{0x1B}instruction manual for{0x03}{0x1B}further information.",
    "Continue game without{0x03}{0x1B}Hard Disk Drive.",
    "P",
    "A",
    "U",
    "S",
    "E",
    "Kingdom{0x0D}{0x06}{eol}Hearts has not been properly{0x03}{0x1B}installed. If you wish to play Kingdom{0x0D}{0x06}{eol}Hearts{0x03}{0x1B},{0x03}{0x1B}please try reinstalling.",
    "There is not enough free space on the system storage device to create new save data. Return to the title screen?",
    "There is not enough free space on the system storage device to create new save data. Return to the title screen?",
    "There is not enough free space on the system storage device to create new save data. Return to the title screen?",
    "The system storage device is not connected. Game progress will not be saved. Begin game?",
    "Now Loading...",
    "Sora",
    "Donald",
    "{0x0D} {eol}Goofy",
    "Tarzan",
    "Pooh",
    "Aladdin",
    "Ariel",
    "Jack",
    "Peter Pan",
    "Beast",
    "{-}{-}{-}",
    "Destiny Islands",
    "Disney Castle",
    "Traverse Town",
    "Wonderland",
    "Deep Jungle",
    "100 Acre Wood",
    "{-}{-}{-}",
    "Agrabah",
    "Atlantica",
    "Halloween Town",
    "Olympus Coliseum",
    "Monstro",
    "Neverland",
    "{-}{-}{-}",
    "Hollow Bastion",
    "End of the World",
    "OK",
    "Yes",
    "No",
    "On",
    "Off",
    "{0x0D}《{0xFF}{0x0E}{0xFF}{0xFF}{0x0F}{0x1B}",
    "{0x0D}《{0xFF}{0x0E}{0xFF}{0xFF}{0x0F}{0x1A}",
    "{0x0D}《{0xFF}{0x0E}{0xFF}{0xFF}{0x0F}{0x19}",
    ":",
    "...",
    "Munny",
    "Time",
    "Done",
    "Stock",
    "Gummi",
    "Keyblade",
    "Key Chain",
    "{0x0F}W",
    "{0x0F}X",
    "{0x0F}b",
    "{0x0F}a",
    "{0x0F}j",
    "{0x0F}i",
    "{0x0F}q",
    "{0x0F}r",
    "{0x0F}s",
    "{0x0F}t",
    "{0x0F}n",
    "{0x0F}c",
    "{0x0F}d",
    "{0x0F}e",
    "{0x0F}f",
    "{0x0F}g",
    "{0x0F}h",
    "Lv.",
    "HP",
    "MP",
    "EXP",
    "AP",
    "Strength",
    "Defense",
    "/",
    "X",
    "Space",
    "NEW GAME",
    "{0x0E}á{0xFF}Select game difficulty level.",
    "{0x0E}Ï{0xFF}Select vibration setting for gamepad.{lf}{lf}{0x0E}R{eol}{0x08}{---}ä{eol}●{0x0C}{0x14}(Settings can be changed at any time in the Config menu.)",
    "Final Mix",
    "Final Mix: Proud",
    "{0x0D}H{eol}Difficulty:{0x0D}{0x08}{eol}{0x0A}",
    "{0x0D}N{eol}Vibration:{0x0D}{0x06}{eol}{0x0A}",
    "Proceed?",
    "{0x0C}{0x18}P{0x0D}{0x14}{eol}A{0x0D}{0x14}{eol}U{0x0D}{0x14}{eol}S{0x0D}{0x14}{eol}E",
    "Continue",
    "Restart",
    "Quit",
    "Continue",
    "Load Game",
    "Load this game?",
    "Item",
    "Price",
    "Total",
    "Items",
    "Equipment",
    "Abilities",
    "Customize",
    "Status",
    "Journal",
    "Config",
    "Save Menu",
    "Use or equip items the party has{lf}obtained.",
    "Equip weapons and accessories.",
    "Assign abilities to the party members.",
    "Displays party members' attributes.",
    "Customize party members' action patterns.",
    "Configure game settings.",
    "Read Jiminy's journal, which contains{lf}his notes and other records.",
    "Displays save menu.",
    "E",
    "Items equipped by Sora.{lf}Select the Items command to use them.",
    "Items equipped by {0x0A}.{lf}Currently assigned fighting style{lf}determines how they will be used.",
    "Items in stock.{lf}Equip to use in the field.",
    "Gummi blocks to be used for{lf}building gummi ships.",
    "Use the item on Sora.",
    "Use the item on {0x0A}.",
    "Discard {0x0A}?",
    "Use item.",
    "Exchange item.",
    "Move item to stock.",
    "Discard item.",
    "",
    "Take item from party member{lf}or stock and equip it.",
    "Take item from stock and equip it.",
    "",
    "Use item.",
    "Exchange item.",
    "",
    "Discard item.",
    "This item cannot be used.",
    "This item cannot be equipped.",
    "Already in stock.",
    "This item cannot be discarded.",
    "Use",
    "Stock",
    "Discard",
    "Exchange",
    "Take Out",
    "Select character to use the item on.",
    "{-}{-}{-}",
    "",
    "Used item.",
    "Restored HP.",
    "Restored MP.",
    "Restored HP and MP.",
    "Powered up Strength.",
    "Powered up Defense.",
    "Raised max AP.",
    "This item will have no effect at this time.",
    "Stock's slot for this item is full.",
    "Stock is empty.",
    "Discarded {0x0A}.",
    "Change whose equipment?",
    "Change Sora's equipment.",
    "Change {0x0A}'s equipment.",
    "{-}{-}{-}",
    "",
    "Remove equipped accessory.",
    "Removing this item lowers AP count.{lf}Remove ability first.",
    "{0x08}{0xFF}{0xFF}—●Keyblade",
    "{0x08}{0xFF}{0xFF}—●Weapon",
    "{0x08}äää●Strength{0x13}N{eol}{0x14}■{eol}{0x0D}{0x04}{eol}{0x0B} {0x03}{eol}{0x0D}{0x09}{eol}►{0x13}{iPotion}{eol}{0x09}{0x0B} {0x03}{eol}",
    "{0x08}{0xFF}{0xFF}—●Accessory",
    "{0x08}OÄu●HP{0x0C}{0x12}{0x0E}{lf}{eol}{0x13}j{eol}{0x08}äää●{0x0B} {0x03}{eol}{0x0D}{0x03}{eol}►{0x13}■{eol}{0x09}{0x0B} {0x03}{eol}",
    "{0x08}O●Ä●MP{0x0C}{0x12}{0x0E}{lf}{eol}{0x13}j{eol}{0x08}äää●{0x0B} {0x03}{eol}{0x0D}{0x03}{eol}►{0x13}■{eol}{0x09}{0x0B} {0x03}{eol}",
    "{0x08}ì{-}{-}●AP{0x0C}{0x12}{0x0E}{lf}{eol}{0x13}j{eol}{0x08}äää●{0x0B} {0x03}{eol}{0x0D}{0x03}{eol}►{0x13}■{eol}{0x09}{0x0B} {0x03}{eol}",
    "{0x08}←←←●STR{0x0C}{0x12}{0x0E}{lf}{eol}{0x13}j{eol}{0x08}äää●{0x0B} {0x03}{eol}{0x0D}{0x03}{eol}►{0x13}■{eol}{0x09}{0x0B} {0x03}{eol}",
    "{0x08}←←←●DEF{0x0C}{0x12}{0x0E}{lf}{eol}{0x13}j{eol}{0x08}äää●{0x0B} {0x03}{eol}{0x0D}{0x03}{eol}►{0x13}■{eol}{0x09}{0x0B} {0x03}{eol}",
    "{-}{-}{-}",
    "Equip selected ability.",
    "Rearrange selected abilities.",
    "Sort the list of abilities.",
    "Remove equipped ability.",
    "Equip",
    "Remove",
    "Rearrange",
    "Sort",
    "Equip/Remove Sora's abilities.",
    "Equip/Remove {0x0A}'s abilities.",
    "Equip/Remove shared abilities.",
    "Shared",
    "By Type",
    "By AP",
    "Equipped",
    "Sort abilities by type.",
    "Sort abilities by AP cost.",
    "Separate equipped and non{-}equipped{lf}abilities.",
    "Sorting completed.",
    "Ability removed.",
    "Ability equipped.",
    "Not enough AP.",
    "Moved item.",
    "Customize Sora.",
    "Customize {0x0A}.",
    "{0x0D}{0x16}{eol}{0x0F}b",
    "{0x0D}{0x16}{eol}{0x0F}a",
    "{0x0D}{0x16}{eol}{0x0F}W",
    "Assign a spell to the shortcut menu.{lf}Cast it with {0x0F}c + {0x0F}b.",
    "Assign a spell to the shortcut menu.{lf}Cast it with {0x0F}c + {0x0F}a.",
    "Assign a spell to the shortcut menu.{lf}Cast it with {0x0F}c + {0x0F}W.",
    "{-}",
    "Unleashes a small burst of flame.{lf}Consumes a small amount of MP.",
    "Unleashes a potent burst of flame.{lf}Consumes a small amount of MP.",
    "Unleashes an incredible burst of flame.{lf}Consumes a small amount of MP.",
    "Unleashes a gust of frost.{lf}Consumes a small amount of MP.",
    "Unleashes a gust of frost.{lf}Longer range than Blizzard.{lf}Consumes a small amount of MP.",
    "Unleashes a gust of frost.{lf}Longest range.{lf}Consumes a small amount of MP.",
    "Calls bolts of lightning to{lf}the target area.{lf}Consumes 1 MP.",
    "Calls a powerful lightning{lf}storm to the target area.{lf}Consumes 1 MP.",
    "Calls a great maelstrom of{lf}lightning to the target area.{lf}Consumes 1 MP.",
    "Restores a little HP to one character.{lf}Consumes 1 MP.",
    "Restores a lot of HP to one character.{lf}Consumes 1 MP.",
    "Restores a massive amount{lf}of HP to one character.{lf}Consumes 1 MP.",
    "Wrings a percentage of HP from the target.{lf}Effective against enemies with lots of HP.{lf}Consumes 1 MP.",
    "Wrings a percentage of HP from the target.{lf}Wider area of effect than Gravity.{lf}Consumes 1 MP.",
    "Wrings a percentage of HP from the target.{lf}Wider area of effect than Gravira.{lf}Consumes 1 MP.",
    "Prevents target from taking action{lf}for a limited time.{lf}Consumes 2 MP.",
    "Prevents targets from taking action for{lf}a limited time. Wide area of effect.{lf}Consumes 2 MP.",
    "Prevents targets from taking action for{lf}a limited time. Widest area of effect.{lf}Consumes 2 MP.",
    "Deploys a barrier that absorbs damage.{lf}Consumes 2 MP.",
    "Deploys a barrier that absorbs damage.{lf}Damages enemies on contact.{lf}Consumes 2 MP.",
    "Deploys a barrier that absorbs damage.{lf}Deflects certain attacks.{lf}Consumes 2 MP.",
    "Remove the spell from the{lf}shortcut menu.",
    "Offensive",
    "Defensive",
    "Conservative",
    "Balanced",
    "Personal",
    "Manual",
    "{0x0C}{0x13}Focuses on attacking.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure manually.",
    "{0x0C}{0x13}Focuses on recovery and defense.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure manually.",
    "{0x0C}{0x13}Focuses on conserving MP and items.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure manually.",
    "{0x0C}{0x13}Good balance of offense and defense.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure manually.",
    "{0x0C}{0x13}Reflects character's own unique style.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure manually.",
    "{0x0C}{0x13}Create your own fighting style.{lf}Switch styles with {0x0F}s{0x0F}t.{lf}Press {0x0F}W to configure.",
    "Regular Attacks",
    "{0x0D} {eol}H{0x0D}{lf}{eol}P{0x0D} {eol} Items",
    "{0x0D} {eol}M{0x0D}{lf}{eol}P{0x0D} {eol} Items",
    "Offensive Magic",
    "Defensive Magic",
    "Advanced Magic",
    "Support Actions",
    "Defensive Moves",
    "Shield Techniques",
    "Special Attacks",
    "Tells how often to perform melee attacks.",
    "Tells how often to use HP{-}restoring items.",
    "Tells how often to use MP{-}restoring items.",
    "Tells how often to use attack magic{lf}that consumes MP.",
    "Tells how often to use restorative and{lf}protective magic that consumes MP.",
    "Tells how often to cast special magic{lf}that consumes MP.",
    "Tells how often to use abilities{lf}that support the party and consume MP.",
    "Tells how often to use restorative and{lf}defensive abilities that consume MP.",
    "Tells how often to perform defensive{lf}actions with the shield.",
    "Tells how often to use offensive{lf}abilities that consume MP.",
    "Constantly",
    "Frequently",
    "Occasionally",
    "Immediately",
    "Only in emergency",
    "Sora's status.{lf}Use {0x0F}s{0x0F}t to turn the page.",
    "{0x0A}'s status.{lf}Use {0x0F}s{0x0F}t to turn the page.",
    "{0x08}《{0xFF}{eol}●Status",
    "{0x08}《{0xFF}{eol}●Equipped",
    "{0x08}《{0xFF}{eol}●Equipped",
    "{0x08}《{0xFF}{eol}●Learned",
    "{0x08}《{0xFF}{eol}●Summon List",
    "{0x08}OÄu●HP{0x08}OÄuu{0x0D}{lf}{eol}/{0x0D}{lf}{eol}Max HP{0x13}{0x06} {0x08}OÄu●{0x0B} {0x03}{eol}{0x08}OÄuu/{0x13}X {0x0B} {0x03}{eol}",
    "{0x08}O●Ä●MP{0x08}O●Äu{0x0D}{eol}{eol}/{0x0D}{lf}{eol}Max MP{0x13}{0x06} {0x08}O●Ä●{0x0B} {0x03}{eol}{0x08}O●Äu/{0x13}X {0x0B} {0x03}{eol}",
    "{0x08}ì{-}{-}●AP{0x08}ì{-}{-}u{0x0D}{lf}{eol}/{0x0D}{lf}{eol}Max AP{0x13}{0x06} {0x08}ì{-}{-}●{0x0B} {0x03}{eol}{0x08}ì{-}{-}u/{0x13}X {0x0B} {0x03}{eol}",
    "{0x08}←←←●STR{0x13}{0xA1}{eol}{0x0B} {eol}{eol}",
    "{0x08}←←←●DEF{0x13}{0xA1}{eol}{0x0B} {eol}{eol}",
    "{0x08}ÁÄO●LV{0x13}{0xA1}{eol}{0x0B} {eol}{eol}",
    "{0x08}À<7●EXP{0x13}{0xA1}{eol}{0x0B} {eol}{eol}",
    "{0x08}←←←●EXP to next level:{0x13}X {0x14}{0xBA}{eol}{0x0B} {eol}{eol}",
    "{0x08}î{-}{-}●Weapon{0x13}{0xBE}{eol}{0x08}äää●Keyblade",
    "{0x13}U{eol}{0x14}P{eol}{0x08}î{-}{-}●Key Chain:{0x13}{0xBE}{eol}{0x08}äää●{0x0A}",
    "{0x08}î{-}{-}●Weapon{0x13}{0xBE}{eol}{0x08}äää●{0x0A}",
    "{0x08}□{0xA5}{0xB1}●Accessories",
    "{0x08}iÏ?●Items",
    "{0x08}ŒŒH●Abilities",
    "{0x08}Ì{iStaff}5●Summon",
    "Auto Lock",
    "On",
    "Off",
    "{-}{-}{-}",
    "Automatically lock on to the nearest{lf}target. Press {0x0F}W to view control{lf}settings.",
    "Target Lock",
    "Auto",
    "Manual",
    "\"Auto\" keeps a target locked until{lf}disengaged. \"Manual\" locks target only{lf}while {0x0F}d is held down.",
    "Camera",
    "Auto",
    "Manual",
    "Select automatic or manual camera{lf}movement. Press {0x0F}W to view control{lf}settings.",
    "Cursor",
    "Set",
    "Default",
    "Choose to whether or not memorize{lf}the cursor's placement on menu screen.",
    "Vibration",
    "On",
    "Off",
    "Turn the vibration on/off.",
    "CAMERA Y{-}Axis",
    "Inverted",
    "Normal",
    "Set Y{-}Axis controls inverted or normal.",
    "Difficulty",
    "Final Mix",
    "Final Mix: Proud",
    "Set the difficulty level of battles{lf}in the game. It cannot be changed{lf}once the game begins.",
    "{0x0C}{0x12}Default Settings",
    "Cancel changes to default settings.",
    "Control Settings",
    "{0x0F}eChange Target",
    "{0x0F}cMagic Shortcut",
    "{0x0F}q{0x0F}r{0x0F}s{0x0F}tSelect Command",
    "{0x0F}iFirst{-}Person View",
    "{0x0F}jMenu/Pause",
    "{0x0F}u{0x0F}v{0x0F}w{0x0F}xMove Sora",
    "{0x0F}dLock On",
    "{0x0F}bCall Help",
    "{0x0F}aSpecial Action",
    "{0x0F}XJump",
    "{0x0F}WExecute Command",
    "{0x0F}lCamera",
    "Change targets while locked on.{lf}Press {0x0F}e to lock on to the next{lf}available target.",
    "Hold down to open the shortcut menu,{lf}which allows you to cast preassigned{lf}spells quickly.",
    "Select various commands.",
    "See the world through Sora's eyes.{lf}Press {0x0F}i again to return to{lf}standard view.",
    "Pause the game and display the{lf}menu screen. The menu cannot be{lf}viewed during battle.",
    "Maneuver Sora.",
    "Lock on to the nearest target.{lf}Sora will automatically direct his{lf}actions toward the locked target.",
    "Call for party members' help. Party{lf}members will direct their actions toward the{lf}locked target when you call for their help.",
    "Execute special ability actions.",
    "Allows Sora to jump.{lf}Hold down longer for a higher jump.",
    "Execute selected command.",
    "Rotate the camera in the field.{lf}Press {0x0F}h to shift the camera{lf}behind Sora.",
    "Characters",
    "Chronicles",
    "101 Dalmatians",
    "Mini Games",
    "Ansem's Report",
    "Trinity List",
    "Save",
    "Party",
    "Gummi Ship",
    "Menu",
    "Save your game.",
    "Switch party members.",
    "Board gummi ship.",
    "Displays main menu.",
    "You can't board the gummi ship.",
    "Board the gummi ship?",
    "New file",
    "Game data",
    "{0x0C}{0x10}Other game data",
    "{0x0C}{0x0F}{0x0D}ú{0xFF}{0x0E}{lf}{eol}MEMORY CARD slot 1",
    "{0x0C}{0x0F}{0x0D}ú{0xFF}{0x0E}{lf}{eol}MEMORY CARD slot 2",
    "Select a SAVE slot.",
    "Checking...",
    "Checking...[{0x0B}{eol}{lf} ]",
    "Save failed.",
    "Unformatted.",
    "Formatting...",
    "Saving...",
    "Overwriting saved data...",
    "Deleting file. Please wait...",
    "Check failed.",
    "Format failed.",
    "Failed to delete file.",
    "",
    "Check failed.",
    "[{0x0B}{eol}{lf} ]",
    "Save file is corrupted.",
    "Unable to read data.{0x0D}{0x0A}{eol}{0x0B}{eol}{eol} ",
    "Cannot save to new file.",
    "Save to new file.",
    "{0x0B}{eol}{lf} :{0x0B}{eol}{lf} {0x0D}o{eol}{0x0B} {0x05}{eol}{0x0D}{0x03}{eol}munny{0x0D}{0x0B}{eol}LV{0x0B}{eol}{0x03}{eol}",
    "{0x0E}{0x06}{eol}Select save file.",
    "Accessing the system storage.{lf}Do not turn your PC off.",
    "Save data is corrupted. {lf}Do you wish to overwrite it?",
    "Overwrite existing file?",
    "Memory card (PS2) is not inserted.",
    "{0x0C}{0x10}{0x0D}°{0xFF}{0x0E}《{0xFF}Memory card (PS2) is unformatted.{lf}{0x0D}°{0xFF}Do you wish to format it?",
    "Format failed.",
    "{0x0C}{0x11}There is not enough free space on the system storage.{lf}At least 92KB of free space is required. ",
    "{0x0C}{0x11}The system storage device has been removed. {lf}Resuming game.",
    "No available party member.",
    "Form your party.",
    "{0x0D}{0xFF}{0xFF}Load Menu",
    "Load",
    "Empty",
    "Save data",
    "{0x0C}{0x10}Other game data",
    "{0x0C}{0x0F}{0x0D}ú{0xFF}{0x0E}{lf}{eol}MEMORY CARD slot 1",
    "{0x0C}{0x0F}{0x0D}ú{0xFF}{0x0E}{lf}{eol}MEMORY CARD slot 2",
    "Select MEMORY CARD slot.",
    "Checking save data...",
    "Checking...[{0x0B}{eol}{lf} ]",
    "Load failed.",
    "Unformatted.",
    "Loading...",
    "Check failed.",
    "Check failed.",
    "[{0x0B}{eol}{lf} ]",
    "Save file is corrupted.",
    "{-}{-}{-}",
    "{0x0B}{eol}{lf} :{0x0B}{eol}{lf} {0x0D}o{eol}{0x0B} {0x05}{eol}{0x0D}{0x03}{eol}munny{0x0D}{0x0B}{eol}LV{0x0B}{eol}{0x03}{eol}",
    "{0x0E}{0x06}{eol}Select data to load.",
    "Accessing the system storage.{lf}Do not turn your PC off.",
    "The system storage device has been removed. {lf}Resuming game.",
    "{0x0C}{0x10}{0x0D}》{0xFF}{0x0E}《{0xFF}Memory card (PS2) not formatted.",
    "The system storage device has been removed. {lf}Resuming game.",
    "Item Synthesis",
    "Created",
    "Need{0x0D}{0x0A}{eol}/{0x0D}{0x0A}{eol}Quantity",
    "Stock",
    "{0x0B} {lf}{eol}/{0x0B}{eol}{lf}{eol}",
    "{0x0C}{0x14}{-}Battle Record{-}",
    "{0x0C}{0x14}Heartless defeated:",
    "{0x0C}{0x14}Times defeated:",
    "{0x0C}{0x14}Attacks deflected:",
    "{0x0C}{0x14}Times hit by an enemy:",
    "{0x0C}{0x14}Total item usage:",
    "{0x0C}{0x14}Party member knockouts:",
    "{0x0C}{0x14}Curative spells cast on friend:",
    "Memory card (PS2) is not inserted{lf}into MEMORY CARD slot 1.",
    "Memory card (PS2) is not inserted{lf}into MEMORY CARD slot 2.",
    "Memory card (PS2) is not inserted{lf}into MEMORY CARD slot 1.",
    "Memory card (PS2) is not inserted{lf}into MEMORY CARD slot 2.",
    "KHFM",
    "KHFMPR",
    "KHFM",
    "KHFMPR",
    "Inverted",
    "Normal",
    "{0x0E}á{0xFF}9",
    "{0x0D}3{eol}9{0x0D}{0x06}{eol}{0x0A}",
    "CAMERA X{-}Axis",
    "Inverted",
    "Normal",
    "Set X{-}Axis controls inverted or normal.",
    "{0x0D}{0x06}{eol}:{0x0D}{0x06}{eol}{0x0C}{0x10}{0x0E}{0x04}{eol}Begin with rare items in easy mode.",
    "{0x0D}{0x06}{eol}:{0x0D}{0x06}{eol}{0x0C}{0x10}{0x0E}{0x04}{eol}A balanced mode recommended for first{-}timers.",
    "{0x0D}{0x06}{eol}:{0x0D}{0x06}{eol}{0x0C}{0x10}{0x0E}{0x04}{eol}Encounter tough enemies for thrilling battles.",
    "Final Mix: Beginner",
    "KHFMBG",
    "KHFMBG",
    "Final Mix: Beginner",
    "",
    "Continue",
    "Skip Scene",
    "{0x0D}{lf}{eol}{0x0E} {eol}{0x0E}{lf}{eol}{0x08}{eol}{eol}{eol}—{iMickey}{0x0D}ñ{0xFF}{0x0E}{0xFE}{0xFF}{0x08}{0xFF}ë{eol}●{iMickey}{0x0D}ó{0xFF}{0x0E} {eol}{0x08}{eol}{eol}{eol}F{iMickey}",
    "{0x0E}á{0xFF}{0x0C}{0x14}Select camera settings.{lf}{0x0E}g{eol}{0x08}{---}ä{eol}●{0x0C}{0x14}(Settings can be changed at any time in the Config menu.)",
    "Auto",
    "Manual",
    "{0x0D}{0x06}{eol}:{0x0D}{0x06}{eol}{0x0E}{0xFD}{0xFF}{0x0C}{0x14}Automatically rotate camera in the field.",
    "{0x0D}{0x06}{eol}:{0x0D}{0x06}{eol}{0x0C}{0x14}Manually rotate camera using {0x0F}l.",
    "{0x0D}d{eol}Camera:{0x0D}{0x06}{eol}{0x0A}",
    "{0x0D}ì{0xFF}P{0x0D}{0x14}{eol}A{0x0D}{0x14}{eol}U{0x0D}{0x14}{eol}S{0x0D}{0x14}{eol}E",
    "Continue",
    "Select World",
    "{0x0E}á{0xFF}9",
    "{0x0D}3{eol}9",
    "9",
    "9",
    "{0x08}äää●MP{0x13}N{eol}{0x14}®{eol}{0x0D}{0x04}{eol}{0x0B} {0x03}{eol}{0x0D}{0x09}{eol}►{0x13}{iPotion}{eol}{0x09}{0x0B} {0x03}{eol}",
    "9",
    "{0x14}I{eol}{0x0F}b: Delete file",
    "Delete selected file?",
    "File has been deleted.",
    "Title Screen",
    "Return to the Title Screen.",
    "You will be returned to the Title Screen.{lf}You will lose your progress if you haven't{lf}saved your game.{lf}Continue?",
    "This contains a restricted character {lf}combination.",
    "Names can only contain up to 5 numbers."
]